apiVersion: v1
kind: ReplicationController
metadata:
  name: jira
spec:
  replicas: 1
  selector:
    app: jira
    tier: application      
  template:
    metadata:
      labels:
        app: jira
        tier: application        
    spec:
      containers:
      - name: jira
        image: cptactionhank/atlassian-jira:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /data/jira/sharedhome
          name: nfs
        - name: jira-configmap
          mountPath: /var/atlassian/jira
      volumes:
      - name: nfs
        # This GCE PD must already exist.
        persistentVolumeClaim:
          claimName: nfs
      - name: jira-configmap
        configMap:
          name: jira-configmap