apiVersion: v1
kind: Service
metadata:
  name: jira
  labels:
    app: jira
    tier: application  
spec:
  selector:
    app: jira
    tier: application  
  type: LoadBalancer
  ports:
  - name: jira
    port: 8080
    targetPort : 8080