apiVersion: v1
kind: ReplicationController
metadata:
  name: jira-nfs-server
spec:
  replicas: 1
  selector:
    app: jira
    tier: nfs-server
  template:
    metadata:
      labels:
        app: jira
        tier: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs
        ports:
          - name: nfs
            containerPort: 2049
        securityContext:
          privileged: true