apiVersion: v1
kind: Service
metadata:
  name: pxc-cluster
  labels:
    app: jira
    unit: pxc-cluster
spec:
  ports:
    - port: 3306
      name: mysql
  selector:
    app: jira
    unit: pxc-cluster