apiVersion: v1
items:
- apiVersion: v1
  data:
    config.yaml: |-
      # Published base URL of the web service.
      # Required if using DNS, Load Balancer, or http->https redirections.
      BASE_URL: http://coreupdate-app:8000

      # (required) Unique secret session string.
      # You can generate a UUID from the command line using the `uuidgen` command
      SESSION_SECRET: "9855056A-AF3A-4DF0-AB6F-BC655F38EB8F"

      # Set this to 'false' if using Google authentication.
      DISABLE_AUTH: true

      # Enables Google OAuth, otherwise set DISABLE_AUTH to 'true'
      # Configure at https://console.developers.google.com
      #GOOGLE_OAUTH_CLIENT_ID:
      #GOOGLE_OAUTH_CLIENT_SECRET:
      # The redirect URL follows this format, substituting the BASE_URL: http://localhost:8000/admin/v1/oauth/login
      #GOOGLE_OAUTH_REDIRECT_URL:

      # Address and port to listen on.
      LISTEN_ADDRESS: ":8000"

      # Postgres database settings.
      # Format: postgres://username:password@host:port/database-name
      DB_URL: "postgres://coreupdate:coreupdate@coreupdate-db:5432/coreupdate?sslmode=disable"
      DBTIMEOUT: 0
      DBMAXIDLE: 0
      DBMAXACTIVE: 100

      # (Optional) sets a path to enable CoreUpdate's static package serving feature.
      # Comment out to disable.
      #STATIC_PACKAGES_DIR: /packages

      # (Optional) enables uploading of package payloads to the server.
      #ENABLE_PACKAGE_UPLOADS: true

      # (Optional) Enable if syncing with upstream CoreUpdate instances.
      # Zero value is disabled.
      # This should be disabled if you plan to synchronize packages manually.
      UPSTREAM_SYNC_INTERVAL: 0

      # (Optional) enables TLS
      #TLS_CERT_FILE:
      #TLS_KEY_FILE:
  kind: ConfigMap
  metadata:
    creationTimestamp: 2016-10-04T01:41:39Z
    name: coreupdate-config
    namespace: coreupdate
    resourceVersion: "667"
    selfLink: /api/v1/namespaces/coreupdate/configmaps/coreupdate-config
    uid: b19257d5-89d3-11e6-96a9-8a6c05fcff96
kind: List
metadata: {}
