apiVersion: v1
kind: Service
metadata:
  namespace: quay-enterprise
  name: quay-enterprise-db
  labels:
    quay-enterprise-component: db
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:
    quay-enterprise-component: db  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: quay-enterprise
  name: quay-enterprise-db
  labels:
    quay-enterprise-component: db
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: quay-enterprise
      labels:
        quay-enterprise-component: db
    spec:
      containers:
      - image: mysql:5.7
        name: quay-enterprise-app
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "quay"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: database  
            readOnly: false
      volumes:
        - hostPath:
            path: /mysql/db
          name: database