apiVersion: v1
kind: ReplicationController
metadata:
  name: webhook
spec:
  replicas: 1
  selector:
    app: webhook    
  template:
    metadata:
      labels:
        app: webhook        
    spec:
      containers:
      - env: 
            - name: Github_BOTUSER
              value: botofalekssaul
            - name: Github_BOTPassword
              value: d2UMc78nDDrErycu
        name: webhook
        image: quay.io/aleks_saul/webhook:v0.3
        imagePullPolicy: Always
