apiVersion: v1
kind: Service
metadata:
  name: webhook
  labels:
    app: webhook
spec:
  selector:
    app: webhook
  type: NodePort
  ports:
  - name: webhook
    protocol: TCP
    port: 9000
    targetPort : 9000
    nodePort: 32050