apiVersion: v1
kind: Service
metadata:
  name: webhook
  labels:
    app: webhook
spec:
  selector:
    app: webhook
  type: LoadBalancer
  ports:
  - name: webhook
    port: 9000
    targetPort : 9000
