  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: jenkinshome
  spec:
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    awsElasticBlockStore:
          volumeID: vol-edd2c050
          fsType: ext4