apiVersion: v1
kind: Service
metadata:
  name: tectonic-console-public
  namespace: tectonic-system
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: tectonic-console-expose
      targetPort: 9000
  selector:
    tectonic-app: console
    tectonic-component: ui