apiVersion: v1
kind: Service
metadata:
  name: tectonic-manager
  namespace: tectonic-system
  labels:
    app: tectonic-manager
    component: install
spec:
  selector:
    app: tectonic-manager
    component: install
  type: NodePort
  ports:
  - name: tectonic-manager
    protocol: TCP
    port: 8080
    nodePort: 32003

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tectonic-manager
  namespace: tectonic-system
  labels:
    app: tectonic-manager
    component: install
spec:
  replicas: 1
  template:
    metadata:
      name: tectonic-manager
      labels:
        app: tectonic-manager
        component: install
    spec:
      containers:
      - name: tectonic-manager
        imagePullPolicy: IfNotPresent
        image: quay.io/aleks_saul/tectonic-manager:0575b920d2c94c4b98e4c5f227e85f73da3c57d0
        command: ["/tectonic-manager", "run"]
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        env:
        - name: TECTONIC_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TECTONIC_LICENSE_FILE
          value: /etc/tectonic/licenses/license
        - name: TECTONIC_MANIFEST_DIR
          value: /etc/tectonic/manifests
        - name: TECTONIC_LISTEN
          value: 0.0.0.0:8080
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi