apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: 2016-09-25T22:15:13Z
  generation: 6
  labels:
    app: tectonic-console
    component: ui
  name: tectonic-console
  namespace: tectonic-system
  resourceVersion: "29171"
  selfLink: /apis/extensions/v1beta1/namespaces/tectonic-system/deployments/tectonic-console
  uid: 87a11913-836d-11e6-b735-063584957832
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tectonic-console
      component: ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tectonic-console
        component: ui
      name: tectonic-console
    spec:
      containers:
      - command:
        - /opt/bridge/bin/bridge
        env:
        - name: BRIDGE_K8S_MODE
          value: in-cluster
        - name: BRIDGE_K8S_AUTH
          value: service-account
        - name: BRIDGE_LISTEN
          value: https://0.0.0.0:80
        - name: BRIDGE_HOST
          valueFrom:
            configMapKeyRef:
              key: console-url
              name: tectonic-config
        - name: BRIDGE_PUBLIC_DIR
          value: /opt/bridge/static
        - name: BRIDGE_USER_AUTH
          value: oidc
        - name: BRIDGE_USER_AUTH_OIDC_ISSUER_URL
          valueFrom:
            configMapKeyRef:
              key: identity-issuer-url
              name: tectonic-config
        - name: BRIDGE_USER_AUTH_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: console-client-id
              name: console-client-credentials
        - name: BRIDGE_USER_AUTH_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: console-client-secret
              name: console-client-credentials
        - name: BRIDGE_KUBECTL_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: kubectl-client-id
              name: kubectl-client-credentials
        - name: BRIDGE_KUBECTL_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: kubectl-client-secret
              name: kubectl-client-credentials
        - name: BRIDGE_TECTONIC_VERSION
          value: 1.3.0
        - name: BRIDGE_CA_FILE
          value: /etc/tectonic-ca-cert-secret/ca-cert
        - name: BRIDGE_TLS_CERT_FILE
          value: /etc/tectonic-console-tls-secret/tls-cert
        - name: BRIDGE_TLS_KEY_FILE
          value: /etc/tectonic-console-tls-secret/tls-key
        - name: BRIDGE_BASE_ADDRESS
          value: https://console.tectonic.alekssaul.com:32000
        image: quay.io/coreos/tectonic-console:vdevel-latest
        imagePullPolicy: IfNotPresent
        name: tectonic-console
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/tectonic-console-tls-secret
          name: tectonic-console-tls-secret
          readOnly: true
        - mountPath: /etc/tectonic-ca-cert-secret
          name: tectonic-ca-cert-secret
          readOnly: true
        - mountPath: /etc/tectonic-config
          name: tectonic-config
          readOnly: true
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
          readOnly: true
        - mountPath: /usr/share/ca-certificates
          name: ca-certs-host
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: coreos-pull-secret
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tectonic-console-tls-secret
        secret:
          secretName: tectonic-console-tls-secret
      - name: tectonic-ca-cert-secret
        secret:
          secretName: tectonic-ca-cert-secret
      - configMap:
          name: tectonic-config
        name: tectonic-config
      - hostPath:
          path: /etc/ssl/certs
        name: ssl-certs-host
      - hostPath:
          path: /usr/share/ca-certificates
        name: ca-certs-host
status:
  availableReplicas: 1
  observedGeneration: 6
  replicas: 1
  updatedReplicas: 1
